const esbuild = require('esbuild');
// Ship this bundle with index.html: classic scripts work over file:// in browsers.
esbuild.buildSync({ entryPoints: ['js/main.js'], bundle: true, format: 'iife',
    platform: 'browser', target: ['es2020'], outfile: 'game.bundle.js',
    banner: { js: '/* Dig: Deep Descent 0.3.0 — generated by npm run build. Edit js/ source modules. */' },
});
